### PR TITLE
Fix method updateStatus in service

### LINKED ISSUE #18: [PATCH /user/status] In /user/status response 401 Unauthorized - always
**Environment**: Firefox 116.0.3 (64-bit).
Reproducible: always.

**Preconditions**
Sign-in us Admin
Moved to Swagger http://localhost:8065/swagger-ui.html#/

**Steps to reproduce**
1. Click on User controller
2. Click on PATCH /user/status
3. Click on 'Try out'
4. Enter valid data

**Actual result**
Response 401 Unauthorized

**Expected result**
Response 200 OK

### LINKED ISSUE #116: [PATCH /user/status] method In /user/status deletes fields of entity
Environment: Firefox 116.0.3 (64-bit).
Reproducible: always.

Preconditions
Moved to Swagger http://localhost:8060/swagger-ui.html#/
Sign-in us Admin

Steps to reproduce

Click on User controller
Click on PATCH /user/status
Click on 'Try out'
Enter valid data
Try do the same with the same user
Actual result
Response 500 Internal Server Error

Expected result
Response 200 OK

### PR DESCRIPTION
**Pull request by Kostya-Pav**
## Summary by CodeRabbit

* **Bug Fixes**
  * Adjusted the endpoint URL for updating user status to ensure correct routing.

* **Refactor**
  * Improved the internal process for updating user status to enhance reliability and maintainability. No changes to the user interface or API signatures.

### CODE REVIEW

**Review by Linney34 — APPROVED** [review]

File: core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java [hunk 1]
```diff
@@ -91,6 +92,24 @@ public final ResponseEntity<Object> handleBadRequestException(BadRequestExceptio
...
+    @ExceptionHandler(PropertyReferenceException.class)
+    public final ResponseEntity<Object> handlePropertyReferenceException(
+        PropertyReferenceException ex, WebRequest request) {
+        ExceptionResponse exceptionResponse = new ExceptionResponse(getErrorAttributes(request));
+        String message = "Invalid sort property: '" + ex.getPropertyName() + "'";
+        exceptionResponse.setMessage(message);
+        log.trace(ex.getMessage(), ex);
+        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(exceptionResponse);
+    }
+
```
Comment (natri0) [inline core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java]: this same method is also in PR #2, why?

Comment (Kostya-Pav) [reply core/src/main/java/greencity/exception/handler/CustomExceptionHandler.java]: The same controller task. I will work with one brunch next time.

**Review by MaksJv — APPROVED** [review]
